### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Damon9420** [DaoD/daod.github.io#1]
朱博士您好，我是武汉纺织大学的一名研一的学生，这周拜读了您的关于KEDIV模型的论文，您的论文对多样性的建模十分合理且有效，以至于我想进一步了解您的实现过程，希望能参考一下您的代码，如果您能在百忙之中回复我的话我将感激不尽，这是我的邮箱hjq_0821@163.com，祝您生活愉快。

**Comment by DaoD** [comment]
谢谢你的关注，关于这篇工作的详细信息请联系一作苏展同学，他的邮箱是suzhan@ruc.edu.cn

**Comment by Damon9420** [comment]
感谢您的回复和帮助，祝你工作顺利。
